name: post
description: Post package for wellness app
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  common_dependencies:
    path: ../common_dependencies
  firebase:
    path: ../firebase
  uuid: ^4.5.2
  flutter_bloc: ^9.1.1
  injectable: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^3.0.0
  injectable_generator: ^2.6.0

flutter:
  uses-material-design: true
